### ISSUE TITLE
docker build **was** failing

### ISSUE THREAD

**Issue by sigmazen** [prakhar1989/FoodTrucks#10]
Hi.   
Firstly, AWESOME overview at docker-curriculum.com ... very methodical and understandable ... thank you :-)    
Just a quick FYI if anyone else hits this issue.   
The `docker build` step was failing for me with `E: Unable to locate package python-pip`.   
It turns out the fix was simply to remove the `-yqq` from the `apt-get update` step, thus:

    RUN apt-get update

Cheers

**Comment by lukewalt** [comment]
I did the same and was still getting...
`The command '/bin/sh -c apt-get -yqq install python-pip python-dev' returned a non-zero code: 100`
so i changed the base image to `FROM ubuntu:latest` in the Dockerfile which fixed the problem!

**Comment by prakhar1989** [comment]
Thanks for pointing this out. Changed the Dockerfile to `ubuntu:latest`.

**Comment by danmostudco** [comment]
Sorry to dredge this up from a long time ago, I was trying out this tutorial this past weekend - it's great and I have really enjoyed it! I'm trying to get the flask application image to build and ran into a similar issue.

I can't get ubuntu to install pip - here is the error message I get during `Step 4/13 : RUN apt-get -yqq install python-pip python-dev curl gnupg`. I tried the above removing of the yqq flag and didn't have any luck.

```
E: Unable to locate package python-pip
The command '/bin/sh -c apt-get -yqq install python-pip python-dev curl gnupg' returned a non-zero code: 100
```
Any thoughts on how I might get the image building? Thanks so much for the great resource; hoping I can get to the finish line!
