### ISSUE TITLE
docker-compose up fails because elasticsearch does not spin up in time

### ISSUE THREAD

**Issue by brightredchilli** [prakhar1989/FoodTrucks#11]
The issue, as far as I can see it, is that on my machine, the es instance does not spin up in 15s(3 retries x 5s from the web service). This causes the web box to exit prematurely. I worked around this by using the [wait-for-it](https://github.com/vishnubob/wait-for-it) script and modifying docker-compose to match. The workarond, in summary:

1. Download wait-for-it.sh file into the flask-app directory
2. Replace `command: python app.py` with `command: ["./wait-for-it.sh", "es:9200", "--", "python", "app.py"]`
3. Run `docker build -t <username>/foodtrucks .` to update the image
4. Re-run `docker-compose up`

This is probably not the best way to do it but I thought I'd record it here in case anyone else has the same issues.

Another obvious solution is simply to increase the timeout. Happy to make a pull request for either.

**Comment by prakhar1989** [comment]
I've updated the compose script with some changes, and hopefully it should be working fine now. Feel free to reopen the issue if it still persists.

**Comment by MattConrad** [comment]
I had (what apparently was) the same issue and brightredchilli's workaround worked for me. Just an FYI.
