### ISSUE TITLE
Docker build fails at RUN npm install

### ISSUE THREAD

**Issue by horialex** [prakhar1989/FoodTrucks#14]
Docker build fails at step:
RUN npm install -> some kinf of certificates error is received after a while

**Comment by KleeTaurus** [comment]
I got the same issue when building the docker image
`The command '/bin/sh -c npm install' returned a non-zero code: 1`

**Comment by KleeTaurus** [comment]
I resolved this problem, change the ubuntu from 14.04 to latest in Dockfile
`
# start from base                                                                                                                                                                                                                                                      FROM ubuntu:latest                                                                                                                                                                                                                                                     MAINTAINER Kevin Lee <klee.taurus@gmail.com>
`

**Comment by prakhar1989** [comment]
Fixed in https://github.com/prakhar1989/FoodTrucks/commit/e7ca0644e122748c1b6e28640be99af1e6b6d66c
