### ISSUE TITLE
Map works with Firefox, but failed with Chrome

### ISSUE THREAD

**Issue by bayareahank** [prakhar1989/FoodTrucks#2]
Running Chrome Version 48.0.2564.82 (64-bit) on Ubuntu, map failed to load with the following messages: 

Failed to initialize WebGLutil.extend._setupPainter @ map.js:674module.exports @ map.js:92(anonymous function) @ app.js:8t @ bootstrap 4f1375e74b4947f995c4:19(anonymous function) @ bootstrap 4f1375e74b4947f995c4:39(anonymous function) @ bootstrap 4f1375e74b4947f995c4:39
map.js:254Uncaught TypeError: Cannot read property 'resize' of undefined

While on Firefox, it looks fine. Maybe it comes from the map library you used.

**Comment by prakhar1989** [comment]
The map library uses webgl to render the map. Can you check if you have webgl enabled in your Chrome?

**Comment by bayareahank** [comment]
Enabled webgl in chrome on ubuntu, problem goes away.
