### ISSUE TITLE
Foodtruck nodes do not display on map.

### ISSUE THREAD

**Issue by TuringTested** [prakhar1989/FoodTrucks#23]
Build step 9 `RUN apt-get install -yq nodejs` gives this warning, then skips subsequent dependencies
`
npm WARN sf-food@0.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
`
I tried using the more recent setup version of 12.x instead of 10.x, but got the same results.

**Comment by prakhar1989** [comment]
Sorry about that.. should be fixed in https://github.com/prakhar1989/FoodTrucks/commit/ec749b2017a9c3f8a869f24b0ae0aaa9a6980284

**Comment by vallsur** [comment]
Hello @prakhar1989 ! 
Thank you very much for this application. I've only started to learn Docker and I've found your FoodTrucks and corresponding Habr blog very useful.
But I faced the same issue :( Search is working fine but no points on the map at all!

I'v got similar feedback as @TuringTested from Docker during image build:
`Step 9/13 : RUN npm install
 ---> Running in 43a136047a20
npm WARN sf-food@0.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})`

and also some more warnings related to REACT:

`WARNING in ./static/build/main.js from UglifyJs
Condition always true [./~/component-emitter/index.js:6,4]
Side effects in initialization of unused variable rootInstance [./~/react-dom/cjs/react-dom.development.js:14449,6]
Side effects in initialization of unused variable props [./~/react-dom/cjs/react-dom.development.js:16481,18]
Side effects in initialization of unused variable _props [./~/react-dom/cjs/react-dom.development.js:16503,18]
Side effects in initialization of unused variable props [./~/react-dom/cjs/react-dom.development.js:16531,12]
Condition left of && always true [./~/react-dom/cjs/react-dom.development.js:23483,16]
Condition always true [./~/react-dom/cjs/react-dom.development.js:23476,8]
Condition always true [./~/react-dom/cjs/react-dom.development.js:23505,12]
Condition always true [./~/react-dom/cjs/react-dom.development.js:23519,12]
Side effects in initialization of unused variable hydrationCallbacks [./~/react-dom/cjs/react-dom.development.js:24625,6]
Side effects in initialization of unused variable IsSomeRendererActing$1 [./~/react-dom/cjs/react-dom.development.js:24574,4]`
...
...
and dependency related warning: urllib3

`Successfully tagged vallsur/foodtrucks-web:latest
app.py  node_modules  package-lock.json  package.json  requirements.txt  static  templates  webpack.config.js
root@c8fe7dda5a69:/opt/flask-app# python3 app.py           
/usr/local/lib/python3.6/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!  RequestsDependencyWarning)`
 
* Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)

App and search is working fine:

`10.10.10.16 - - [16/Jan/2021 22:12:23] "GET / HTTP/1.1" 200 -
10.10.10.16 - - [16/Jan/2021 22:12:23] "GET /static/styles/main.css HTTP/1.1" 200 -
10.10.10.16 - - [16/Jan/2021 22:12:23] "GET /static/build/main.js HTTP/1.1" 200 -
10.10.10.16 - - [16/Jan/2021 22:12:25] "GET /static/icons//android-icon-192x192.png HTTP/1.1" 200 -
10.10.10.16 - - [16/Jan/2021 22:12:44] "GET /search?q=burgers HTTP/1.1" 200 -`

I tried different Elastic Search versions (I thaught it could be the reason) but all gave the same result:
no points on the map at all ;(

`root@c8fe7dda5a69:/opt/flask-app# curl es:9200
{
  "name" : "Scarlet Spiders",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.1.1",
    "build_hash" : "40e2c53a6b6c2972b3d13846e450e66f4375bd71",
    "build_timestamp" : "2015-12-15T13:05:55Z",
    "build_snapshot" : false,
    "lucene_version" : "5.3.1"
  },
  "tagline" : "You Know, for Search"
}
`
or
`root@b377b3d47c5d:/opt/flask-app# curl es:9200
{
  "name" : "NNmhf-i",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "pAQBFnavRTWjX18ad-whGw",
  "version" : {
    "number" : "6.3.2",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "053779d",
    "build_date" : "2018-07-20T05:20:23.451332Z",
    "build_snapshot" : false,
    "lucene_version" : "7.3.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
`

Please consider what am I doing wrong ? 
Thank you in advance!
