### ISSUE TITLE
Web container cannot contact es using docker-compose

### ISSUE THREAD

**Issue by Partha-Mukherjee-G2H** [prakhar1989/FoodTrucks#5]
The problem is that a name for ES is created automatically (foodtrucks_es_1) and the network (foodtrucks_default). However, the app.py refers to host (es) which doesn't exist. Is there to have the docker-compose script set this as an environment parameter that gets populated in the container at launch time and picked up by app.py?

**Comment by prakhar1989** [comment]
This should be fixed in the updated `docker-compose.yml`. Feel free to reopen if this persists.
