### ISSUE TITLE
App does not display correctly in Firefox

### ISSUE THREAD

**Issue by ronnyfm** [prakhar1989/FoodTrucks#7]
<img width="1270" alt="screen shot 2016-11-22 at 4 21 18 am" src="https://cloud.githubusercontent.com/assets/265763/20520106/1ee6191a-b06b-11e6-88f2-05db43aeb702.png">

**Comment by prakhar1989** [comment]
Is this still an issue with #8?

**Comment by ronnyfm** [comment]
Yes, it is still an issue.

**Comment by prakhar1989** [comment]
Sorry, seems like an issue with the javascript. Should be fixed now - here's a screenshot with the latest version of Firefox

<img width="470" alt="Screen Shot 2020-04-12 at 6 26 40 PM" src="https://user-images.githubusercontent.com/649249/79084906-42e9d180-7ceb-11ea-9084-b264e56802e4.png">
